databases:
  - name: campground-db
    databaseName: campground
    user: campground
    region: singapore

services:
  - type: web
    name: campground
    env: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: campground-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
