# Generated by Django 4.2.1 on 2023-05-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0001_initial"),
        ("campings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campground",
            name="tags",
            field=models.ManyToManyField(related_name="campgrounds", to="tags.tag"),
        ),
    ]
